node:internal/assert:11
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (node:internal/assert:11:11)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:457:7)
    at #link (node:internal/modules/esm/module_job:440:34)
    at new ModuleJobSync (node:internal/modules/esm/module_job:413:17)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:522:11)
    at #link (node:internal/modules/esm/module_job:440:34)
    at new ModuleJobSync (node:internal/modules/esm/module_job:413:17)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:522:11)
    at #link (node:internal/modules/esm/module_job:440:34)
    at new ModuleJobSync (node:internal/modules/esm/module_job:413:17) {
  code: 'ERR_INTERNAL_ASSERTION'
}
Thrown at:
    at assert (node:internal/assert:11:11)
    at getModuleJobForRequire (node:internal/modules/esm/loader:457:7)
    at #link (node:internal/modules/esm/module_job:440:34)
    at ModuleJobSync (node:internal/modules/esm/module_job:413:17)
    at getModuleJobForRequire (node:internal/modules/esm/loader:522:11)
    at #link (node:internal/modules/esm/module_job:440:34)
    at ModuleJobSync (node:internal/modules/esm/module_job:413:17)
    at getModuleJobForRequire (node:internal/modules/esm/loader:522:11)
    at #link (node:internal/modules/esm/module_job:440:34)
    at ModuleJobSync (node:internal/modules/esm/module_job:413:17)


Node.js v24.4.1
